"""Where competitor binaries are looked for, and what is recorded about them.

Every msplat row in the README was produced by a binary under /tmp, which a
reboot deletes -- so the competitor half of the headline table could not be
regenerated by anyone. These tests pin the two things that prevents: the
resolver points somewhere durable, and what got installed is recorded.
"""
from __future__ import annotations

import json

import pytest

from bench import paths
from bench.compare import setup_competitors as sc


@pytest.fixture
def third_party(tmp_path, monkeypatch):
    monkeypatch.setenv("METAL_GAUSS_THIRD_PARTY", str(tmp_path / "tp"))
    for var in ("METAL_GAUSS_MSPLAT", "METAL_GAUSS_BRUSH", "METAL_GAUSS_SPIRULA"):
        monkeypatch.delenv(var, raising=False)
    return tmp_path / "tp"


def test_msplat_is_not_looked_for_under_tmp(third_party):
    """/tmp does not survive a reboot; that is how the binaries were lost."""
    assert not paths.msplat_bin().startswith("/tmp/")
    assert str(third_party) in paths.msplat_bin()


def test_every_competitor_resolves_under_third_party(third_party):
    for resolve in (paths.msplat_bin, paths.brush_bin, paths.spirula_bin):
        assert str(third_party) in resolve()


def test_an_explicit_path_still_wins(third_party, monkeypatch):
    monkeypatch.setenv("METAL_GAUSS_MSPLAT", "/somewhere/else/msplat-train")
    assert paths.msplat_bin() == "/somewhere/else/msplat-train"


def test_manifest_is_empty_when_nothing_is_installed(third_party):
    assert sc.read_manifest() == {}


def test_manifest_survives_a_corrupt_file(third_party):
    third_party.mkdir(parents=True)
    (third_party / "versions.json").write_text("{not json")
    assert sc.read_manifest() == {}


def test_recording_a_version_keeps_the_other_entries(third_party):
    sc._record("msplat", version="1.1.4")
    sc._record("brush", tag="v0.3.0")
    m = sc.read_manifest()
    assert m["msplat"]["version"] == "1.1.4"
    assert m["brush"]["tag"] == "v0.3.0"
    assert "installed_at" in m["msplat"]


def test_check_counts_what_is_missing(third_party, capsys):
    assert sc.check() == 3
    out = capsys.readouterr().out
    assert out.count("MISS") == 3


def test_check_reports_the_recorded_version(third_party, capsys):
    binp = third_party / "msplat" / "bin" / "msplat-train"
    binp.parent.mkdir(parents=True)
    binp.write_text("#!/bin/sh\n")
    sc._record("msplat", version="1.1.4")
    assert sc.check() == 2
    out = capsys.readouterr().out
    assert "1.1.4" in out
