"""Install the competitor trainers, pinned, somewhere that survives a reboot.

Every competitor number in the README was produced by a binary that no longer
exists on the machine that produced it. `msplat_bin()` defaulted to
`/tmp/cmp_msplat/bin/msplat-train`, and /tmp does not survive a restart, so the
competitor half of the headline table could not be regenerated by anyone --
including its author. That is the same problem as the quarantined benchmark
results, one level down: a number whose protocol cannot be restated.

So: installs go under `third_party()` (override with METAL_GAUSS_THIRD_PARTY),
versions are pinned here rather than resolved to "latest" at install time, and
what actually got installed is written to `versions.json` next to them, so a
sweep row can state which build produced it.

    python bench/compare/setup_competitors.py --check       # report, install nothing
    python bench/compare/setup_competitors.py --only msplat

What this does NOT do is pretend the three are equally scriptable:

  * msplat is a pinned pip install into its own venv. Fully determined.
  * Brush ships a prebuilt macOS binary. The release ASSET is resolved from the
    GitHub API for the pinned tag rather than a URL written from memory, so a
    renamed asset fails loudly instead of downloading nothing.
  * spirula builds from source with CMake, and this repository never recorded
    the exact incantation that worked -- only that it worked. The build here is
    the ordinary one; if it fails it says so and points at the traps that
    bench/compare/STATUS.md already documents, rather than papering over it.
"""
from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
import time
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))
from bench.paths import (brush_bin, competitor_versions, msplat_bin,  # noqa: E402
                         spirula_bin, third_party)

# Pinned. A benchmark against "whatever was latest that day" is not repeatable,
# and these are the versions bench/compare/STATUS.md reports as working.
MSPLAT_VERSION = "1.1.4"
BRUSH_TAG = "v0.3.0"
BRUSH_REPO = "ArthurBrussee/brush"
BRUSH_ASSET_MATCH = "aarch64-apple-darwin"
SPIRULA_REPO = "https://github.com/harry7557558/spirula-studio"


def _run(cmd: list[str], **kw) -> subprocess.CompletedProcess:
    print("    $ " + " ".join(str(c) for c in cmd), flush=True)
    return subprocess.run([str(c) for c in cmd], text=True, **kw)


def _manifest_path() -> Path:
    return third_party() / "versions.json"


# The reader lives in bench.paths: a sweep needs it without importing an
# installer that reaches for the network at import time.
read_manifest = competitor_versions


def _record(name: str, **fields) -> None:
    m = read_manifest()
    m[name] = {"installed_at": time.strftime("%Y-%m-%dT%H:%M:%S"), **fields}
    _manifest_path().parent.mkdir(parents=True, exist_ok=True)
    _manifest_path().write_text(json.dumps(m, indent=2, sort_keys=True) + "\n")


def install_msplat() -> bool:
    """pip install into a dedicated venv, so its torch cannot collide with ours."""
    venv = third_party() / "msplat"
    venv.mkdir(parents=True, exist_ok=True)
    if not (venv / "bin" / "python").exists():
        if _run([sys.executable, "-m", "venv", str(venv)]).returncode:
            return False
    spec = f"msplat[cli]=={MSPLAT_VERSION}"
    if _run([venv / "bin" / "pip", "install", "--quiet", spec]).returncode:
        return False
    got = _run([venv / "bin" / "pip", "show", "msplat"], capture_output=True)
    version = next((l.split(": ", 1)[1] for l in got.stdout.splitlines()
                    if l.startswith("Version: ")), "?")
    _record("msplat", version=version, requested=MSPLAT_VERSION,
            bin=str(venv / "bin" / "msplat-train"))
    return (venv / "bin" / "msplat-train").exists()


def _brush_asset_url() -> str | None:
    """Resolve the macOS asset for the pinned tag, rather than guessing a URL."""
    api = f"https://api.github.com/repos/{BRUSH_REPO}/releases/tags/{BRUSH_TAG}"
    req = urllib.request.Request(api, headers={"Accept": "application/vnd.github+json",
                                               "User-Agent": "metal-gauss-setup"})
    with urllib.request.urlopen(req, timeout=30) as fh:
        rel = json.loads(fh.read())
    for asset in rel.get("assets", []):
        if BRUSH_ASSET_MATCH in asset["name"]:
            return asset["browser_download_url"]
    names = ", ".join(a["name"] for a in rel.get("assets", [])) or "none"
    print(f"    no asset matching {BRUSH_ASSET_MATCH!r} in {BRUSH_TAG}; assets: {names}")
    return None


def install_brush() -> bool:
    url = _brush_asset_url()
    if not url:
        return False
    dest = third_party() / "brush"
    dest.mkdir(parents=True, exist_ok=True)
    archive = dest / url.rsplit("/", 1)[-1]
    print(f"    downloading {url}", flush=True)
    urllib.request.urlretrieve(url, archive)
    shutil.unpack_archive(str(archive), str(dest))
    archive.unlink()
    ok = Path(brush_bin()).exists()
    if ok:
        os.chmod(brush_bin(), 0o755)
        _record("brush", tag=BRUSH_TAG, bin=brush_bin(), source=url)
    else:
        print(f"    unpacked, but {brush_bin()} is not where bench/paths.py "
              f"expects it; contents: "
              f"{[p.name for p in dest.iterdir()]}")
    return ok


def install_spirula() -> bool:
    """Source build. See the module docstring on why this one is best-effort."""
    src = third_party() / "spirula-studio"
    if not src.exists():
        if _run(["git", "clone", "--depth", "1", SPIRULA_REPO, str(src)]).returncode:
            return False
    head = _run(["git", "-C", str(src), "rev-parse", "HEAD"], capture_output=True)
    build = src / "build"
    # SS_BACKEND defaults to "cuda" (cmake/SsOptions.cmake), so a plain
    # `cmake -S . -B build` on a Mac fails in CMakeDetermineCUDACompiler
    # looking for a CUDA toolkit that cannot exist here. The Vulkan backend is
    # the one that runs on MoltenVK, and is what the benchmarked build used.
    if _run(["cmake", "-S", str(src), "-B", str(build),
             "-DCMAKE_BUILD_TYPE=Release", "-DSS_BACKEND=vulkan"]).returncode:
        print("    cmake configure failed. spirula needs the Vulkan SDK / "
              "MoltenVK; see bench/compare/STATUS.md")
        return False
    if _run(["cmake", "--build", str(build), "--parallel"]).returncode:
        print("    build failed; see bench/compare/STATUS.md")
        return False
    ok = Path(spirula_bin()).exists()
    if ok:
        _record("spirula", commit=head.stdout.strip()[:12], bin=spirula_bin(),
                source=SPIRULA_REPO)
    return ok


INSTALLERS = {"msplat": install_msplat, "brush": install_brush,
              "spirula": install_spirula}
RESOLVERS = {"msplat": msplat_bin, "brush": brush_bin, "spirula": spirula_bin}


def check() -> int:
    manifest = read_manifest()
    missing = 0
    print(f"third_party: {third_party()}")
    for name, resolve in RESOLVERS.items():
        p = Path(resolve())
        rec = manifest.get(name, {})
        ver = rec.get("version") or rec.get("tag") or rec.get("commit") or "unrecorded"
        if p.exists():
            print(f"  {name:<9} OK    {ver:<14} {p}")
        else:
            print(f"  {name:<9} MISS  {'':<14} {p}")
            missing += 1
    if missing:
        print(f"\n{missing} missing. Install with: "
              f"python bench/compare/setup_competitors.py")
    return missing


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--only", nargs="*", choices=sorted(INSTALLERS),
                    default=sorted(INSTALLERS))
    ap.add_argument("--check", action="store_true",
                    help="report what is installed and exit")
    a = ap.parse_args()

    if a.check:
        raise SystemExit(1 if check() else 0)

    third_party().mkdir(parents=True, exist_ok=True)
    failed = []
    for name in a.only:
        if Path(RESOLVERS[name]()).exists():
            print(f"[{name}] already present at {RESOLVERS[name]()}")
            continue
        print(f"[{name}] installing")
        if INSTALLERS[name]():
            print(f"[{name}] ok -> {RESOLVERS[name]()}")
        else:
            print(f"[{name}] FAILED")
            failed.append(name)

    print()
    check()
    if failed:
        raise SystemExit(f"failed: {', '.join(failed)}")


if __name__ == "__main__":
    main()
